Repository jacobrs/stocklion, pull requests merged in 2018-02, with the labels that each got.

#5 Added FEN Converter
  CMakeLists.txt
  converters/FENConverter.cpp
  converters/FENConverter.h
  datastructures/Board.cpp
  datastructures/Board.h
  datastructures/pieces/Bishop.cpp
  datastructures/pieces/Bishop.h
  datastructures/pieces/King.cpp
  datastructures/pieces/King.h
  datastructures/pieces/Knight.cpp
  datastructures/pieces/Knight.h
  datastructures/pieces/Pawn.cpp
  datastructures/pieces/Pawn.h
  datastructures/pieces/Piece.cpp
  datastructures/pieces/Piece.h
  datastructures/pieces/Queen.cpp
  datastructures/pieces/Queen.h
  datastructures/pieces/Rook.cpp
  datastructures/pieces/Rook.h
  main.cpp
Labels: enhancement

#6 Converts/pgn converter
  CMakeLists.txt
  converters/PGNConverter.cpp
  converters/PGNConverter.h
  datastructures/Board.cpp
  datastructures/Board.h
  datastructures/pieces/Pawn.cpp
  main.cpp
  util/UnicodeTable.cpp
  util/UnicodeTable.h
Labels: enhancement

#13 Added function to display unicode table
  datastructures/Board.cpp
  datastructures/Board.h
  datastructures/pieces/Bishop.cpp
  datastructures/pieces/Bishop.h
  datastructures/pieces/King.cpp
  datastructures/pieces/King.h
  datastructures/pieces/Knight.cpp
  datastructures/pieces/Knight.h
  datastructures/pieces/Pawn.cpp
  datastructures/pieces/Pawn.h
  datastructures/pieces/Piece.h
  datastructures/pieces/Queen.cpp
  datastructures/pieces/Queen.h
  datastructures/pieces/Rook.cpp
  datastructures/pieces/Rook.h
  main.cpp
  util/UnicodeTable.cpp
  util/UnicodeTable.h
Labels: enhancement

#14 Added base for google tests
  .gitignore
  CMakeLists.txt
  CMakeLists.txt.in
  tests/converters/PGNConverterTests.cpp
Labels: enhancement

#18 Check and move restrictions
  .travis.yml
  CMakeLists.txt
  converters/PGNConverter.cpp
  datastructures/Board.cpp
  datastructures/Board.h
  datastructures/pieces/Bishop.cpp
  datastructures/pieces/Bishop.h
  datastructures/pieces/King.cpp
  datastructures/pieces/King.h
  datastructures/pieces/Knight.cpp
  datastructures/pieces/Knight.h
  datastructures/pieces/Pawn.cpp
  datastructures/pieces/Pawn.h
  datastructures/pieces/Piece.cpp
  datastructures/pieces/Piece.h
  datastructures/pieces/Queen.cpp
  datastructures/pieces/Queen.h
  datastructures/pieces/Rook.cpp
  datastructures/pieces/Rook.h
  detectors/CheckDetector.cpp
  detectors/CheckDetector.h
  main.cpp
  tests/datastructures/pieces/BishopTests.cpp
  util/VectorComparator.cpp
  util/VectorComparator.h
Labels: core

#19 Comparators + Tests
  CMakeLists.txt
  datastructures/Board.cpp
  datastructures/Board.h
  datastructures/pieces/Bishop.cpp
  datastructures/pieces/Bishop.h
  datastructures/pieces/King.cpp
  datastructures/pieces/King.h
  datastructures/pieces/Knight.cpp
  datastructures/pieces/Knight.h
  datastructures/pieces/Pawn.cpp
  datastructures/pieces/Pawn.h
  datastructures/pieces/Piece.cpp
  datastructures/pieces/Piece.h
  datastructures/pieces/Queen.cpp
  datastructures/pieces/Queen.h
  datastructures/pieces/Rook.cpp
  datastructures/pieces/Rook.h
  tests/datastructures/BoardTests.cpp
  tests/datastructures/pieces/PieceTests.cpp
Labels: enhancement

#20 Wip fix travis build
  .travis.yml
  converters/PGNConverter.cpp
  converters/PGNConverter.h
  datastructures/Board.cpp
  datastructures/pieces/Bishop.cpp
  datastructures/pieces/Bishop.h
  datastructures/pieces/King.cpp
  datastructures/pieces/King.h
  datastructures/pieces/Knight.cpp
  datastructures/pieces/Knight.h
  datastructures/pieces/Pawn.cpp
  datastructures/pieces/Pawn.h
  datastructures/pieces/Piece.cpp
  datastructures/pieces/Piece.h
  datastructures/pieces/Queen.cpp
  datastructures/pieces/Queen.h
  datastructures/pieces/Rook.cpp
  datastructures/pieces/Rook.h
  main.cpp
  util/UnicodeTable.cpp
  util/UnicodeTable.h
Labels: enhancement

#21 [WIP] Codecov
  .travis.yml
  CMakeLists.txt
Labels: enhancement

#22 More Tests
  CMakeLists.txt
  converters/FENConverter.cpp
  datastructures/pieces/Bishop.cpp
  datastructures/pieces/King.cpp
  datastructures/pieces/Knight.cpp
  datastructures/pieces/Pawn.cpp
  datastructures/pieces/Queen.cpp
  datastructures/pieces/Rook.cpp
  tests/converters/FENConverterTests.cpp
  tests/datastructures/BoardTests.cpp
  tests/datastructures/pieces/BishopTests.cpp
  tests/datastructures/pieces/KingTests.cpp
  tests/datastructures/pieces/KnightTests.cpp
  tests/datastructures/pieces/PawnTests.cpp
  tests/datastructures/pieces/QueenTests.cpp
  tests/datastructures/pieces/RookTests.cpp
  tests/util/VectorComparatorTests.cpp
Labels: enhancement

#23 Check detector tests
  CMakeLists.txt
  datastructures/Board.cpp
  datastructures/Board.h
  tests/datastructures/BoardTests.cpp
  tests/detectors/CheckDetectorTests.cpp
Labels: tests

#24 Tests/add pgn tests
  converters/PGNConverter.cpp
  tests/converters/PGNConverterTests.cpp
Labels: tests

#25 Fixed codacy issues
  converters/FENConverter.cpp
  datastructures/pieces/Piece.cpp
  datastructures/pieces/Piece.h
  util/UnicodeTable.cpp
  util/UnicodeTable.h
Labels: enhancement
